title: Eping
email: 'eping[@]live.com'
description: Eping
baseurl: ''
url: ''
twitter_username: cneping
github_username: eping
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-admin
